### ISSUE TITLE
Errors when compile in release mode

### ISSUE THREAD

**Issue by shiftinthinking** [Devolutions/sspi-rs#9] opened 2020-12-22 19:41 UTC
I was experimenting with this crate and had things working well until I tried compiling in release mode.  I created a small test and got the same problem.

The following program runs fine when compiled in debug, but returns  

Error { error_type: InvalidToken, description: "The parameter is incorrect. (os error 87)" }' 

when compiled in release.  

```
use sspi::winapi::Ntlm;
use sspi::{AuthIdentity, CredentialUse, Sspi};

fn main() {
    let identity = AuthIdentity {
        username: "xxxxx".to_owned(),
        password: "yyyyy".to_owned(),
        domain: None
    };

    let mut ntlm = Ntlm::new();

    ntlm
        .acquire_credentials_handle()
        .with_credential_use(CredentialUse::Outbound)
        .with_auth_data(&identity)
        .execute()
        .unwrap();
}
```

I'm using the following version of the compiler.

$ rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  c:\rust\rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.48.0 (7eac88abb 2020-11-16)

**Comment by sduquette-devolutions** [comment] 2021-01-04 18:23
I do not get the error when building your sample in release mode. Could you attach your Cargo.lock file? I wonder if it reproduces with a specific version of a dependency.

**Comment by shiftinthinking** [comment] 2021-01-04 18:55
I tried it with a new project so this should just include the minimum dependencies.  Attached is my cargo.lock file.


[Cargo.lock.zip](https://github.com/Devolutions/sspi-rs/files/5766299/Cargo.lock.zip)

**Comment by RRRadicalEdward** [comment] 2023-02-09 10:35
I can't reproduce it. I close it as obsolete

**Closed by RRRadicalEdward** 2023-02-09 10:35 UTC
